### ISSUE TITLE
The plotter does not print ideal circles.

### ISSUE THREAD

**Issue by dukelanovic** [shihaipeng03/Walldraw#2]
Please have a look what my plotter plots if I want it to plot circles:

https://1drv.ms/u/s!AigMv2zY7zgLpNZ8Bx7XR2EL1XyWfA?e=4ccTlk

can you please help me. Please contact me my e-mail is dukelanovic@yahoo.de . 
WeChat: +4915907015505 .

Xie Xie Ni

Thank you

**Comment by dukelanovic** [comment]
I added the support for the A4988 stepper motors from the Tango board to your software. 
Please contact me.
Your software code is working but on my plotter the dimensions are not correct.
https://1drv.ms/u/s!AigMv2zY7zgLpNZ8Bx7XR2EL1XyWfA?e=4ccTlk
can you please help me. Please contact me my e-mail is dukelanovic@yahoo.de .
WeChat: +4915907015505 .

**Comment by shihaipeng03** [comment]
This one only supports BYJ28 motors. I don't know much about A4988 either. I'm sorry about that.

**Comment by dukelanovic** [comment]
At the end of the code you will find my function according A4988. Your software is great, but I do not know why your software is not working on my 2 x 2 m Plotter. I use 1/16th of the stepper motor resolution. (3200 steps per revolution)
    Am Sonntag, 1. August 2021, 05:07:06 MESZ hat shihaipeng03 ***@***.***> Folgendes geschrieben:  
 
 


This one only supports BYJ28 motors. I don't know much about A4988 either. I'm sorry about that.

**Comment by dukelanovic** [comment]
Further I forgot to say that we can infiltrate the software from Makelangelo and program our own serial commands so that the plotter can be manually driven by the computer. I have the Makelangelo software running over here on Eclipse. I am very happy for having this correspondence with you. - Xie Xie Ni :)
Sincerely, 
Pavle Dukanovic
    Am Sonntag, 1. August 2021, 16:40:25 MESZ hat Pavle Dukanovic ***@***.***> Folgendes geschrieben:  
 
  At the end of the code you will find my function according A4988. Your software is great, but I do not know why your software is not working on my 2 x 2 m Plotter. I use 1/16th of the stepper motor resolution. (3200 steps per revolution)
    Am Sonntag, 1. August 2021, 05:07:06 MESZ hat shihaipeng03 ***@***.***> Folgendes geschrieben:  
 
 


This one only supports BYJ28 motors. I don't know much about A4988 either. I'm sorry about that.

**Comment by dukelanovic** [comment]
I added the possibillity to run serial commands on your software. Watch the end of the code and in loop.
    Am Sonntag, 1. August 2021, 16:47:29 MESZ hat Pavle Dukanovic ***@***.***> Folgendes geschrieben:  
 
  Further I forgot to say that we can infiltrate the software from Makelangelo and program our own serial commands so that the plotter can be manually driven by the computer. I have the Makelangelo software running over here on Eclipse. I am very happy for having this correspondence with you. - Xie Xie Ni :)
Sincerely, 
Pavle Dukanovic
    Am Sonntag, 1. August 2021, 16:40:25 MESZ hat Pavle Dukanovic ***@***.***> Folgendes geschrieben:  
 
  At the end of the code you will find my function according A4988. Your software is great, but I do not know why your software is not working on my 2 x 2 m Plotter. I use 1/16th of the stepper motor resolution. (3200 steps per revolution)
    Am Sonntag, 1. August 2021, 05:07:06 MESZ hat shihaipeng03 ***@***.***> Folgendes geschrieben:  
 
 


This one only supports BYJ28 motors. I don't know much about A4988 either. I'm sorry about that.
